[theme]
primaryColor = "#00a8e8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1f2937"
textColor = "#fafafa"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"
